services:
  api:
    build: ./api
    container_name: spirited-todo-api
    volumes:
      - ./api:/app
      - todo_sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/data/todo.db
    depends_on:
      - web
  web:
    build: ./web
    container_name: spirited-todo-web
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
volumes:
  todo_sqlite_data: 