export enum ErrorCode {
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  HIGH_PRIORITY_LIMIT = "HIGH_PRIORITY_LIMIT",
  INVALID_INPUT = "INVALID_INPUT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
