name: API CI

on:
  pull_request:
    paths:
      - 'api/**'
      - 'web/**'
      - 'docker-compose.yml'
      - 'Makefile'

jobs:
  lint-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build all Docker images
        run: docker-compose build
      - name: Lint API (pylint)
        run: make lint-api
      - name: Check API formatting (black)
        run: make lint-api-format
      - name: Run API tests
        run: make test-api 