name: API CI

on:
  pull_request:
    paths:
      - 'api/**'
      - 'web/**'
      - 'docker-compose.yml'
      - 'Makefile'

jobs:
  lint-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build all Docker images
        run: docker compose build
      - name: Lint, format, and sort imports in API (isort, black, pylint)
        run: make lint-api-all
      - name: Run API tests
        run: make test-api
      - name: Run frontend tests
        run: make test-web
      - name: Run frontend lint
        run: make lint-web